name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository code
        uses: actions/checkout@v3

      - name: Use Node.js v22.12.0
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0

      - name: Install dependencies
        run: npm ci
        # "npm ci" は package-lock.jsonに従って完全再現インストール

      - name: Lint
        run: npm run lint
        # ここでエラーが出たらCIが失敗

      - name: Build
        run: npm run build
        # 例: webpack等でビルドする

      - name: Test
        run: npm test
        # 例: Jestなどのテストが走る
